# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-3903492-capc-ub22-is/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k325tffg900-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_packages_1.0.0/pcie_datalink_pkg.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_transmit_1.0.0/axis_retry_fifo.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_packages_1.0.0/pcie_tlp_pkg.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_receive_1.0.0/axis_user_demux.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_packages_1.0.0/pcie_phy_pkg.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_receive_1.0.0/block_alignment.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_scrambler_1.0.0/byte_scramble.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_receive_1.0.0/data_handler.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_receive_1.0.0/dllp2tlp.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_receive_1.0.0/dllp_fc_update.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_receive_1.0.0/dllp_handler.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_config_1.0.0/pcie_config_reg_pkg.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_receive_1.0.0/dllp_receive.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_transmit_1.0.0/dllp_transmit.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_transmit_1.0.0/frame_symbols.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_scrambler_1.0.0/gen1_scramble.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_scrambler_1.0.0/gen3_byte_scramble.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_scrambler_1.0.0/gen3_scramble.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_transmit_1.0.0/lane_management.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_receive_1.0.0/ordered_set_handler.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_transmit_1.0.0/os_generator.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_receive_1.0.0/pack_data.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_config_1.0.0/pcie_cfg_wrapper.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_config_1.0.0/pcie_config_decode.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_config_1.0.0/pcie_config_handler.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_config_1.0.0/pcie_config_mux.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_config_1.0.0/pcie_config_reg.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_crc_1.0.0/pcie_datalink_crc.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_core_1.0.0/pcie_datalink_init.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_core_1.0.0/pcie_datalink_layer.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_core_1.0.0/pcie_flow_ctrl_init.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_crc_1.0.0/pcie_lcrc16.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_ltssm_1.0.0/pcie_ltssm_downstream.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_kc705_1.0.0/src/pcie_phy_core/pcie_phy_top.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_receive_1.0.0/phy_receive.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_transmit_1.0.0/phy_transmit.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_transmit_1.0.0/retry_management.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_transmit_1.0.0/retry_transmit.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_phy_scrambler_1.0.0/scrambler.sv
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_dllp_transmit_1.0.0/tlp2dllp.sv
    }
      rt::read_verilog {
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/arbiter.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/async_fifo_1.1.0-r1/rtl/async_fifo.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/axis_adapter.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/axis_arb_mux.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/axis_async_fifo.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/axis_fifo.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/axis_register.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/async_fifo_1.1.0-r1/rtl/fifomem.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_crc_1.0.0/pcie_crc8.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_crc_1.0.0/pcie_dllp_crc8.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pipe_wrapper_1.0.0/src/pipe_wrapper.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_axis_1.0.0/rtl/priority_encoder.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/async_fifo_1.1.0-r1/rtl/rptr_empty.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/async_fifo_1.1.0-r1/rtl/sync_r2w.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/async_fifo_1.1.0-r1/rtl/sync_w2r.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/async_fifo_1.1.0-r1/rtl/wptr_full.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pipe_wrapper_1.0.0/src/xilinx_pcie_mmcm.v
      /tools/C/research/pcie/pcie_datalink_layer/build/fusesoc_pcie_pcie_kc705_1.0.0/xsim_v-xsim/src/fusesoc_pcie_pcie_kc705_1.0.0/example/pcie_top_kc705.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/EP_MEM.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/PIO.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/PIO_EP.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/PIO_EP_MEM_ACCESS.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/PIO_RX_ENGINE.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/PIO_TO_CTRL.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/PIO_TX_ENGINE.vhd
      /tools/C/research/pcie/pcie_datalink_layer/tb/vivado_sim/pcie_7x_0_ex/imports/pcie_app_7x.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pcie_top_kc705
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    set_param edifin.funnel true
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-3903492-capc-ub22-is/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
